[package]
name = "arrow_lib"
version = "0.1.1"
edition = "2021"

[dependencies]
tracing = "0.1.37"
crossbeam-channel = "0.5.8"
chrono = { version = "0.4.1", features = ["serde"]}
#bigdecimal = {version = "0.4.1", features = ["serde"]}
