[package]
name = "arrow_lib"
version = "0.1.1"
edition = "2021"

[dependencies]
common_lib = { path="../common_lib"}
tracing = "0.1.37"
crossbeam-channel = "0.5.8"
chrono = { version = "0.4.1", features = ["serde"]}
